project_id = "hrdbdoovgvjtteeyowoi"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.edit-image]
verify_jwt = false

[functions.analyze-music]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.summarize-text]
verify_jwt = false
